### PR TITLE
added instanceAttachments

### PR DESCRIPTION
**Pull request by geomapdev**
Updated to use instanceAttachments map  { filename: url }  to resolve image URLs on previously submitted records.

In response to: https://github.com/kobotoolbox/enketo-express/issues/50

### CODE REVIEW

**Comment by MartijnR** [comment]
Thanks a lot! Very useful feature. My goal is test this before the 17th of this month.

**Comment by geomapdev** [comment]
Do I need to address the failed check?  I didn't change any tests, but may need to.

**Comment by MartijnR** [comment]
It would be great. Some exception is occuring for a GET API call: https://travis-ci.org/kobotoolbox/enketo-express/jobs/208785012

Otherwise, no worries. I can do this.

**Comment by geomapdev** [comment]
Maybe just needed these 2 lines added.  
https://github.com/geomapdev/enketo-express/commit/df420061464b984b4a58a10b2f1cd914cdf97cab
(have not tested yet)

**Comment by MartijnR** [comment]
Squashed and merged! Thanks a lot! 👍 

There was a bug (explaining the failing test) caused by double-JSON-parsing. I tested only via Enketo's API like this (so not using KoBo):

```bash
curl --user enketorules: -d "server_url=https://api.ona.io/enketo&form_id=widgets&instance=<widgets><text_widgets><my_string>mart</my_string></text_widgets><media_widgets><my_image>test.jpg</my_image></media_widgets></widgets>&instance_id=someUUID&return_url=https://enketo.org&instance_attachments[test.jpg]=http://www.kobotoolbox.org/sites/toolbox/themes/Rise_sub/logo.png&instance_attachments[bla]=blu" http://localhost:8005/api/v2/instance
```

This bug probably means that the KoBo-side code is passing a stringified JSON object (so it was double JSON-stringified as well by the time it ended up in Enketo's storage). So that should probably fixed in the KoBo PR(s).

API docs have also been updated: https://apidocs.enketo.org/v2#/post-instance

**Comment by geomapdev** [comment]
Thank you!  

Kobocat is passing a JSON string, but this seemed to be the best way to convert the python dictionary to JSON and pass it to enketo:

https://github.com/kobotoolbox/kobocat/pull/334/files#diff-cec4d5661d03adabc14e2f6efc04e7b6R559

Should I handle it differently in kobocat, or should enketo expect a JSON string?

**Comment by MartijnR** [comment]
It should be done differently because of the way Enketo already accepts `defaults` (existing API feature see e.g. [here](https://apidocs.enketo.org/v2#/post-survey). Otherwise, we could have considered stringified JSON. Defaults are very similar and in fact I think it's feasible to combine both defaults and instance_attachments in the future for some webform views.

So it should be passed as an application/x-www-form-urlencoded object.

**Comment by geomapdev** [comment]
ok I removed json.dumps(..) so it will pass a dictionary instead of a string, which will be form encoded by responses.post

https://github.com/kobotoolbox/kobocat/pull/334/files#diff-cec4d5661d03adabc14e2f6efc04e7b6R559

**Pull request closed without merging**
