### PR TITLE
Proposal on lines 62 & 70 & 97

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by MartijnR** [comment]
Hi @kant, thanks so much! Would you perhaps be able to make the changes in https://www.transifex.com/enketo/enketo-express/dashboard/ instead? That is our source for translations (and these json files are exported from that source). We need to keep the source up-to-date because we have multiple translators working on the same files.

**Comment by kant** [comment]
I will in a couple of hours, please, be patient... Kudos and brand new year!

**Comment by kant** [comment]
@MartijnR Waiting the approval to join the Spanish team in Transifex!

**Comment by kant** [comment]
@MartijnR Transifex registration: done
Translations: done

**Comment by MartijnR** [comment]
Thank you!  Your changes will be in the next release!

**Pull request closed without merging**
