### PR TITLE
Use local configured "themes supported" if present

### PR DESCRIPTION
**Pull request by ukanga**

### CODE REVIEW

**Comment by MartijnR** [comment]
Thanks ukanga. What's the use case for this change?

**Comment by ukanga** [comment]
The "themes supported" config is not used at all, this change allows you to use the configured "themes supported" in config.json.

**Comment by ukanga** [comment]
Looking at this, if `themes supported` is configured it will be wise to only include the ones that actually exist in the themes file path.

**Comment by ukanga** [comment]
@MartijnR This was important for me to provide a custom list of enabled themes when building the `webform-combined-min.js`. I have now refactored the code to use a function that will only return a valid list of themes if a list is provided as is likely to happen when you have a configured your list of themes.

**Comment by MartijnR** [comment]
Thanks Ukang'a! I don't understand what you meant with:

> The "themes supported" config is not used at all,

It is used [here](https://github.com/kobotoolbox/enketo-express/blob/master/public/js/src/module/gui.js#L119) (on the client for the future mobile app, but am rethinking that due to flickering).

But the ability to disable themes seems valuable. Thanks for adding the tests too!!

**Comment by MartijnR** [comment]
merged!

**Pull request closed without merging**
