### PR TITLE
A functioning Docker service. Closes kobotoolbox/kpi/#416.

### PR DESCRIPTION
**Pull request by esmail**
Closes kobotoolbox/kpi#416.

### CODE REVIEW

**Comment by tinok** [comment]
Closes kobotoolbox/kpi#416

**Comment by MartijnR** [comment]
Cool stuff! Thanks. Some comments and questions:

1. Can you add a small section to the readme including prerequisites please?
2. Is this meant for development? production? local? public? Currently, it seems the encryption key is given great importance (production) but the redis configuration is only suitable for development (using one instance), so it's not matching.
3. Please put all new files (except Dockerfile) in /setup/docker. I can re-organize the vagrant-specific and the common setup files, to create a neat structure (or include this work if you have time).
4. I was wondering if we could not use python in this repo... but that could be for later. Sorry I had to mention that. I'm probably being way too anal about this.

I look forward to trying this out (but haven't use docker yet, so will await the Readme for instructions).

**Comment by esmail** [comment]
P.S. If you want to test, use ef05d85; the last commit won't work until merged into master.

**Comment by MartijnR** [comment]
Thanks. Didn't realize python was in build-essential.

I haven't managed to install docker properly on my computer yet, but squashed and merged it anyway.

**Pull request closed without merging**
