### PR TITLE
Add support for specifying manifest URL in transform/xform

### PR DESCRIPTION
**Pull request by m4tx**
This allows the form logo to be included in form preview

### CODE REVIEW

**Comment by MartijnR** [comment]
Thanks! Much appreciated.

I wonder if specifying `?form=..&manifest=...` has any advantage to specifying `?server=...&id=widgets`. If so, could you elaborate on the use case? Is it a fixed form logo you always want to display, but you're not looking into solving (other) media labels?

If not, see demo: https://enke.to/preview?server=https://api.ona.io/enketo&id=widgets

**Comment by m4tx** [comment]
Oh, I think I should have made clear that this comes with corresponding kpi patch that uses this: kobotoolbox/kpi#1141.

So, the use case is "preview" feature in kpi - when you click it, it loads `https://<enketo_url>/preview?form=https://<kpi_url>/asset_snapshots/<form_id>.xml` inside an iframe. The obvious problem is that the xform does not contain any information about the media - so neither the form logo nor any other image is displayed on the preview - but they appear on the deployed form! It makes the preview feature useless (as it is supposed to show how the form will look like when it's deployed, but unfortunately it does not display some things).

The solution for that would be the `&manifest=...` parameter I introduced in this Pull Request. In that case, `https://<enketo_url>/preview?form=https://<kpi_url>/asset_snapshots/<form_id>.xml&manifest=https://<kobocat_url>/xformsManifest/<form_pk>` would be displayed, so both all new fields and the media files can be loaded. This URL also should make clear why `?server=...&id=...` is insufficient in this case - we have the XForm on one server (kpi's - the changes were not yet sent to kobocat), and the manifest file on another (kobocat's).

I hope this explanation is clear and the existence of this PR is now justified.

**Comment by MartijnR** [comment]
Thanks for clarifying. So if I understand correctly, the use case is:

1. form and media have already been published on KC and are available in the regular kc manifest
2. user is **editing** the form and wants to preview the changes with the already uploaded media

Is that correct?

**Comment by m4tx** [comment]
Yes, exactly.

**Comment by MartijnR** [comment]
Cool. That would be nice to have!

In that case, I wonder if we should avoid adding a 4th preview query parameter and instead re-use `server`. So we would have ?form=URI&server=URI. Not sure yet though. Will think about this.

What do you think?

**Comment by m4tx** [comment]
Good point! Seems like a way to make kpi's patch less "magic" (as there would be no need to find kobocat's internal form's ids) as well as enketo's (probably?) simpler. Please note however that we'll still need to use `id` URL parameter (so it would look like `?form=URI&server=URI&id=string`), as AFAIK we cannot obtain the form ID neither from xform file nor its URL.

**Comment by MartijnR** [comment]
Ah yes, I see what you mean with still needing `id` as well. 

Thanks!

@dorey, this is to provide media in KoBoForm form previews for forms that have already been launched in KC. I just wanted to check if you had any ideas for the future whereby KoBoForm previews have media **without** having been launched on KC (E.g. users would upload media labels while building a form, and this would be available during editing a form as well). That would be good to know.

**Comment by dorey** [comment]
> I just wanted to check if you had any ideas for the future whereby KoBoForm previews have media without having been launched on KC.

Yes, we will start managing media files on form drafts in this phase of KPI work. This includes logos.

> E.g. users would upload media labels, and form logo, while building a form, and this would be available during editing a form as well. That would be good to know (maybe some kind of temporary /formList)

I like the idea of a temporary `/formList`. I'd like to think about what this should include and how it would work with KPI drafts.

We closed [the associated PR on kpi](https://github.com/kobotoolbox/kpi/pull/1141) for now, so I think we can close this PR and reopen if passing a manifest parameter seems like a good idea in the future.

**Comment by MartijnR** [comment]
Yes, that sounds good. This wider KF preview feature would solve all media-in-preview use cases. Thanks @m4tx !

**Pull request closed without merging**
