### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by esmail**
Based on the apparent stability of the the Docker instance running at ee.kobotoolbox.org, I think these updates are ready to move out of a separate branch and into `master`.

### CODE REVIEW

**Comment by MartijnR** [comment]
Looks fancy! 

This is a production server, right? Or can it also be used locally for development?

**Comment by esmail** [comment]
Should be fine for either, though now that you mention it, I haven't tested a local configuration for a bit. Let me give it a try and I'll let you know how it goes.

**Comment by MartijnR** [comment]
Wow! Docker is massively complex! I think I'm going to wait for the next deployment technology myself ;).

This is all fine with me. Just two questions:

Do you still think we should also present this as a way for developers to run Enketo locally, or should best to see this as a production deployment option? I can change the readme after merge.

Is it is possible to move any of the 3 docker-specific files to /setup/.../.../?

**Comment by esmail** [comment]
I'd say most of the complexity is the Docker Compose aspects of bringing together the two Redis containers with Enketo (though it's possible all three of these could be rolled into one image) and putting Nginx out front, as well as the Nginx configurations that support both SSL servers and local-only setups.

I think it's feasible as a development environment (I use our `kobo-docker` it for KoBo development and testing). But as it is, you'll have to pay a 20+ second `docker-compose build enketo_express && docker-compose up -d` tax when you want to see new changes live.

Anyway, I can move `docker-compose.yml` out of the root. Similarly, `Dockerfile` can apparently be [moved](http://stackoverflow.com/a/34392052/1877326). Not sure about `.dockerignore`; I'll have to test.

**Comment by MartijnR** [comment]
Thanks. Sounds good. Very cool that those files can be moved. I was having some reservations about deployment files in the root (since there are so many different ways to deploy).

**Comment by MartijnR** [comment]
@esmail, if you haven't moved it yet, just keep Dockerfile in root. We also cannot move Vagrantfile, and developers may look for these files (without reading the readme). Moving docker-compose.yml would be great (and .dockerignore if possible). If it's a pain, just tell me and we'll merge now. I like the idea of KoBo updating their Enketo servers frequently, and getting this merged will help, I think ;).

**Comment by esmail** [comment]
@MartijnR, just got around to moving `docker-compose.yml` out of the root. Let me know if you want me to do anything else.

**Comment by MartijnR** [comment]
👍  Thanks

merged with d53766d55cbdfa20ce682110ef0a001becc4491a

**Pull request closed without merging**
